### ISSUE TITLE
微信分享后再次分享，没有图片

### ISSUE THREAD

**Issue by baibonjwa** [eleduck/maskhero#40]
https://developers.weixin.qq.com/doc/offiaccount/OA_Web_Apps/JS-SDK.html#66

相关代码: https://github.com/eleduck/maskhero/blob/master/public/index.html#L60
Signature: https://svc.eleduck.com/api/v1/wechat/signature?url=<url>

**Comment by YuniorZen** [comment]
貌似分享有问题 @BAI-Bonjwa  指派给我吧
