### ISSUE TITLE
适配新的 API 格式

### ISSUE THREAD

**Issue by baibonjwa** [eleduck/maskhero#5]
实现一个脚本，将不同城市的表单数据通过金数据 API 同步到一个新建的汇总表中。
服务器上每隔一段时间执行一次同步数据
前端读取新的汇总表来显示数据

金数据 API 使用说明：https://help.jinshuju.net/articles/entry-api

需要汇总的表单 TOKEN：
con81f
Ukw1aQ
SzsFuT
nQPfAu
fCKyxY

**Comment by Donvi** [comment]
这里说明一下汇总数据源和目标地址吧

**Comment by baibonjwa** [comment]
> 这里说明一下汇总数据源和目标地址吧

@Donvi 更新了需要汇总的表单 Token。
目标地址是指汇总总表吗？这几个城市表结构都一样，就从当前的几个城市复制出来一个新的当汇总表就可以了。用金数据中添加数据的 API 将其他城市的信息同步过去。
注意可能需要不同的 API key 和 secret，自己新建的汇总表应该需要自己的 API key secret 来调用
