### ISSUE TITLE
a little optimization

### ISSUE THREAD

**Issue by YuniorZen** [eleduck/maskhero#55]
为了项目不走向臃肿且方便后续自愿者参与（尽管现在就一个页面 哈哈），建议对项目进行一次小优化，分两步走：

- 抽离配置、资源数据和http业务请求，方便复用与维护。
- 分离页面中UI作为组件模块使用和维护，保持app入口单一。

**Comment by baibonjwa** [comment]
👍

**Comment by YuniorZen** [comment]
进度更新：分离页面中UI作为组件模块使用和维护，保持app入口单一。

目前已经完成的组件拆分包括头部、底部、帮助我们、赞助商、自愿者。
![image](https://user-images.githubusercontent.com/6168355/78525696-78ce1800-780a-11ea-9137-666895824c96.png)

待拆分的组件有：
援助地图、爱的留言机。

有没有小伙伴愿意加入剩下的优化任务呢？
分支名：Issue55-optimization

**Comment by YuniorZen** [comment]
> 进度更新：分离页面中UI作为组件模块使用和维护，保持app入口单一。
> 
> 目前已经完成的组件拆分包括头部、底部、帮助我们、赞助商、自愿者。
> ![image](https://user-images.githubusercontent.com/6168355/78525696-78ce1800-780a-11ea-9137-666895824c96.png)
> 
> 待拆分的组件有：
> 援助地图、爱的留言机。
> 
> 有没有小伙伴愿意加入剩下的优化任务呢？
> 分支名：Issue55-optimization


进度同步：援助地图、爱的留言机组件拆分完成
