### ISSUE TITLE
后端合并数据脚本优化

### ISSUE THREAD

**Issue by baibonjwa** [eleduck/maskhero#72]
脚本文件位置：https://github.com/eleduck/maskhero/blob/master/scripts/merge_data.py
脚本作用：将多个城市的 form 数据合并到一个中供前端调用

优化：
- [x] 合并后数据保持录入时间的顺序（可能需要加个时间戳列）
- [x] 添加合并数据表相关数据列（微信相关数据列和“是否已领取”列）

相关表单：
澳大利亚-堪培拉 https://jinshuju.net/forms/RQlAnN
加拿大-渥太华 https://jinshuju.net/forms/lOg5eU
加拿大-布兰登 https://jinshuju.net/forms/con81f
加拿大-温尼伯 https://jinshuju.net/forms/Ukw1aQ
合并数据表：https://jinshuju.net/forms/1slVSR

如无法访问上述表的，注册金数据后 @BAI-Bonjwa 添加权限

**Comment by shitou6004** [comment]
@BAI-Bonjwa 已注册金数据 账号  jefferys1024@163.com

**Comment by baibonjwa** [comment]
> @BAI-Bonjwa 已注册金数据 账号 [jefferys1024@163.com](mailto:jefferys1024@163.com)

@shitou6004 已添加访问权限

**Comment by shitou6004** [comment]
已提交新分支  issus75_mergedata

**Comment by baibonjwa** [comment]
> 已提交新分支 issus75_mergedata

👍 我测试下

**Comment by baibonjwa** [comment]
> 已提交新分支 issus75_mergedata

可以分享下你测试的表单不，我的邮箱 baibonjwa@gmail.com

**Comment by shitou6004** [comment]
我这边测试时通过其他方式进行测试的，没有直接使用表单插入的方式，源数据的获取表单是使用的原脚本中的表单进行的数据查询
