### ISSUE TITLE
增加各个板块之间的距离

### ISSUE THREAD

**Issue by baibonjwa** [eleduck/maskhero#78]
Figma UI: https://www.figma.com/file/y5OvmknBbxOGdxD6bEekdV/%E7%94%B5%E9%B8%AD-%E4%B8%8E%E5%AD%90%E5%90%8C%E8%A2%8D?node-id=874%3A0

增加各个板块之间的距离，包括桌面版和移动版，具体细节见上方 UI 链接（下图为最终效果）
![image](https://user-images.githubusercontent.com/6316425/79058602-8c61fe80-7ca2-11ea-8e39-614443634996.png)
![image](https://user-images.githubusercontent.com/6316425/79058631-e662c400-7ca2-11ea-80bd-c46154ff02f4.png)

**Comment by YuniorZen** [comment]
搞起来
