### ISSUE TITLE
志愿者分组及提示模块

### ISSUE THREAD

**Issue by baibonjwa** [eleduck/maskhero#87]
Web 端添加志愿者详细信息及分组功能，如图
![image](https://user-images.githubusercontent.com/6316425/80047309-ae2f7100-853f-11ea-81c9-840340c022ee.png)

https://www.figma.com/file/y5OvmknBbxOGdxD6bEekdV/%E7%94%B5%E9%B8%AD-%E4%B8%8E%E5%AD%90%E5%90%8C%E8%A2%8D?node-id=874%3A0

**Comment by YuniorZen** [comment]
@BAI-Bonjwa  指给我吧
