### ISSUE TITLE
用 API 返回的信息替换援助图记的模拟信息

### ISSUE THREAD

**Issue by baibonjwa** [eleduck/maskhero#9]
用 API 返回的信息替换援助图记的模拟信息

UI/UX：https://www.figma.com/file/y5OvmknBbxOGdxD6bEekdV/%E7%94%B5%E9%B8%AD-%E4%B8%8E%E5%AD%90%E5%90%8C%E8%A2%8D?node-id=0%3A1

表单 API：https://jinshuju.net/api/v1/forms/JDuzxU/entries 
录入页面: https://jinshuju.net/f/JDuzxU

![image](https://user-images.githubusercontent.com/6316425/77814242-2bef9080-70ea-11ea-8c2e-4b74e2aa3757.png)

**Comment by greatghoul** [comment]
能说的更详细一些吗？

**Comment by baibonjwa** [comment]
> 能说的更详细一些吗？

好的，稍后更新一波具体点儿的问题描述。
